### ISSUE TITLE
Zugriff auf den Contao Manager wird benötigt

### ISSUE THREAD

**Issue by V15** [oveleon/product-installer#3]
Ich habe gerade versucht, die [Demo-Dateien](https://www.contao-thememanager.com/files/demo/contao-thememanager-demo-1.0.0.content) des ThemeManagers über die Produktverwaltung bzw. den "Product Installer" zu installieren (so wie [hier](https://contao-thememanager.github.io/core/#/guides/step-by-step/demo?id=_3-demo-installieren-und-einrichten) beschrieben). Das scheitert aber leider daran, dass der Zugriff auf den Contao Manager benötigt wird:

> Contao Manager
> 
> Damit der Product Installer die erforderlichen Abhängigkeiten installieren kann, benötigt dieser Zugriff auf den Contao Manager. Um fortzufahren installieren Sie bitte den Contao Manager und starten Sie den Installationsprozess erneut.
> 
> Contao Manager muss installiert werden

Wie kann ich den Zugriff herstellen?

Ich habe eine aktuelle Contao 4.13.x Installation frisch aufgesetzt, da ich den "Product Installer" leider nicht in einer Contao 5.2.x installieren konnte (Fehlermeldung im Contao Manager: Contao 4.13 nötig). Könnt ihr da noch die Kompatibilität zu 5.2.x herstellen?

**Comment by doishub** [comment]
Hallo Thorsten,
der Installer müsste dir in dieser Maske einen "Autorisieren"-Button zur Verfügung stellen, über diesen kannst du dein Projekt für den Contao Manager verifizieren.

Die Kompatibilität zu Contao 5.2 schaue ich mir an.

**Comment by doishub** [comment]
Mit Version [1.0.4](https://github.com/oveleon/product-installer/releases/tag/1.0.4) ist der Installer nun auch für Contao 5.x freigegeben.

**Comment by doishub** [comment]
Wie in der Maske steht, scheint der Contao Manager nicht installiert zu sein. Wie in der Doku beschrieben gibt es hier 3 Fälle die eintreten können:
https://contao-thememanager.github.io/core/#/guides/step-by-step/demo?id=contao-manager-authentifizierung

**Comment by doishub** [comment]
![image](https://github.com/oveleon/product-installer/assets/48379929/82199610-9e47-4eaa-8d30-612c2223ba52)

Das ist korrekt, hierbei handelt es sich um die "Bridge" für den ThemeManager (`1.0.1`).

**Comment by V15** [comment]
Der Fehler liegt aktuell vermutlich daran, dass ich nicht alle Core-Bestandteile installiert hatte (Newsletter, Kommentare und FAQ waren nicht installiert)
